---
- hosts: webserver
  remote_user: ubuntu
  become: true 
  tasks:

  - name: Install packages
    apt:
      update_cache: yes
      state: latest
      force_apt_get: yes

  - name: Install apache2
    apt:
      name: apache2
      update_cache: yes
      state: latest

  - name: Set timezone
    timezone:
      name: Africa/Lagos

  - name: Print host name to server
    tags: printf
    shell: echo "<h1>This is my server name $(hostname -f)</h1>" > /var/www/html/index.html

  - name: Restart apache2
    tags: restart  
    service: 
      name: apache2
      state: restarted